default_agent: runtime
agents:
  runtime:
    name: runtime
    entrypoint: /home/ubuntu/projects/aws-ai-ml-workshop-kr/genai/aws-gen-ai-kr/20_applications/08_bedrock_manus/use_cases/05_insight_extractor_strands_sdk_workshop_phase_2/runtime.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::615299776985:role/agentcore-runtime-role
      execution_role_auto_create: false
      account: '615299776985'
      region: us-west-2
      ecr_repository: 615299776985.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-runtime
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: runtime-6nu10MBeiT
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:615299776985:runtime/runtime-6nu10MBeiT
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-runtime-builder
      execution_role: arn:aws:iam::615299776985:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-d92c6a81b2
      source_bucket: bedrock-agentcore-codebuild-sources-615299776985-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
