default_agent: langgraph_bedrock
agents:
  langgraph_bedrock:
    name: langgraph_bedrock
    entrypoint: /home/ubuntu/projects/aws-ai-ml-workshop-kr/genai/aws-gen-ai-kr/13_agentcore/tutorials/01-AgentCore-runtime/01-hosting-agent/02-langgraph-with-bedrock-model/langgraph_bedrock.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::615299776985:role/agentcore-langgraph_bedrock-role
      execution_role_auto_create: false
      account: '615299776985'
      region: us-west-2
      ecr_repository: 615299776985.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-langgraph_bedrock
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: langgraph_bedrock-fKcSg6DMAK
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:615299776985:runtime/langgraph_bedrock-fKcSg6DMAK
      agent_session_id: 83dd56ec-b2ad-4c8e-9d8c-272328db2d0a
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration: null
